#
# Usage:
#   conda env create --file=.conda/environment.yml -n rbc
#   python setup.py develop
#   pytest -sv .

name: rbc
channels:
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.7
  - setuptools
  - numba>=0.55
  - llvmlite
  - clang
  - clangxx
  - pytest
  - packaging
  - tblib
  - thriftpy2
  - netifaces
