package:
  name: rbc
  version: 0.7.3

source:
  git_url: https://github.com/xnd-project/rbc.git
  git_rev: v0.7.3
  #git_url: ../

test:
  requires:
    - pytest
  commands:
    - pytest -sv -r s -k "not test_python_version" --pyargs rbc
  imports:
    - rbc
    - rbc.thrift

requirements:
  build:
    - python
    - setuptools
  host:
    - cffi
    - python
    - setuptools
    - pip
  run:
    - cffi
    - python
    - thriftpy2
    - tblib
    - llvmlite >=0.29
    - numba >=0.52
    - netifaces

about:
  home: https://github.com/xnd-project/rbc
  license: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/../LICENSE.txt'
