package:
  name: rbc
  version: 0.1.0.dev2

source:
  git_url: https://github.com/xnd-project/rbc.git
  git_rev: v0.1.0.dev2
  #git_url: ../

test:
  requires:
    - pytest
  commands:
    - pytest -sv -r s --pyargs rbc
  imports:
    - rbc
    - rbc.thrift

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pytest-runner
    - pytest
    - thriftpy2
    - tblib
    - llvmlite >=0.29
    - numba
    - netifaces
  run:
    - python
    - thriftpy2
    - tblib
    - llvmlite
    - numba
    - six
    - netifaces

about:
  home: https://github.com/xnd-project/rbc
  license: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/../LICENSE.txt'
